name: Validate PR
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: review pull request thing
        uses: christopherscott/conventional-pull-request-action@github-context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
