name: 'Test typescript-action'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: review pull request thing
        uses: christopherscott/conventional-pull-request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
